"""
Generates src/lib/ngss-standards.ts from scripts/ngss-evidence-data.json
"""
import json

with open("scripts/ngss-evidence-data.json", encoding="utf-8") as f:
    data = json.load(f)


def esc(s):
    if not s:
        return ""
    return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


lines = [
    "/**",
    " * Complete NGSS Performance Expectations with Evidence Statement data.",
    " * Generated by scripts/scrape-ngss-evidence.py from official NGSS Evidence Statements.",
    " * Source: https://www.nextgenscience.org/evidence-statements",
    " */",
    "",
    "export interface NgssStandard {",
    "  code: string;",
    "  title: string;",
    "  gradeBand: 'MS' | 'HS';",
    "  domain: 'PS' | 'LS' | 'ESS' | 'ETS';",
    "  dci: string;",
    "  sep: string;",
    "  ccc: string;",
    "  /** Clarification statement from NGSS Evidence Statements */",
    "  clarification?: string;",
    "  /** Assessment boundary from NGSS Evidence Statements */",
    "  boundary?: string;",
    "  /** Observable features of student performance from NGSS Evidence Statements */",
    "  observableFeatures?: string;",
    "}",
    "",
    "export const NGSS_STANDARDS: NgssStandard[] = [",
]

for e in data:
    lines.append("  {")
    lines.append(f"    code: '{e['code']}',")
    lines.append(f"    title: `{esc(e['title'])}`,")
    lines.append(f"    gradeBand: '{e['gradeBand']}',")
    lines.append(f"    domain: '{e['domain']}',")
    lines.append(f"    dci: '{e['dci']}',")
    lines.append(f"    sep: '{e['sep']}',")
    lines.append(f"    ccc: '{e['ccc']}',")
    if e.get("clarification"):
        lines.append(f"    clarification: `{esc(e['clarification'])}`,")
    if e.get("boundary"):
        lines.append(f"    boundary: `{esc(e['boundary'])}`,")
    if e.get("observableFeatures"):
        lines.append(f"    observableFeatures: `{esc(e['observableFeatures'])}`,")
    lines.append("  },")

lines.append("];")
lines.append("")

content = "\n".join(lines)
with open("src/lib/ngss-standards.ts", "w", encoding="utf-8") as f:
    f.write(content)

print(f"Generated ngss-standards.ts with {len(data)} standards")
print(f"File size: {len(content):,} bytes")
